name: Auto-update CITATION.cff (setup.cfg-based)

on:
    release:
        types: [published]

jobs:
    update-citation:
        runs-on: ubuntu-24.04

        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.13]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install doi2cff
              run:
                  pip install
                  git+https://github.com/citation-file-format/doi2cff

            - name: Create and switch to PR branch
              run: |
                  git checkout -b update-citation-${{ github.event.release.tag_name }}

            - name: Fetch latest Zenodo DOI
              env:
                  ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
              run: |
                  python scripts/fetch_latest_doi.py > latest_doi.txt
                  echo "Latest DOI: $(cat latest_doi.txt)"

            - name: Update CITATION.cff
              run: doi2cff update $(cat latest_doi.txt)

            - name: Commit updated CITATION.cff
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add CITATION.cff
                  git commit -m "Update CITATION.cff with latest Zenodo DOI"
                  git push origin update-citation-${{ github.event.release.tag_name }}

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: update-citation-${{ github.event.release.tag_name }}
                  base: master
                  title:
                      'Update CITATION.cff for ${{ github.event.release.tag_name
                      }}'
                  body: |
                      Automated update of `CITATION.cff` using latest Zenodo DOI:
                      - Release: ${{ github.event.release.tag_name }}
                      - DOI: $(cat latest_doi.txt)
