name: Auto-update CITATION.cff (setup.cfg-based)

on:
    release:
        types: [published]

jobs:
    update-citation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install doi2cff
              run:
                  pip install
                  git+https://github.com/citation-file-format/doi2cff

            - name: Fetch latest Zenodo DOI
              env:
                  ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
              run: |
                  python scripts/fetch_latest_doi.py > latest_doi.txt
                  echo "Latest DOI: $(cat latest_doi.txt)"

            - name: Update CITATION.cff
              run: doi2cff update $(cat latest_doi.txt)

            - name: Commit updated CITATION.cff
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add CITATION.cff
                  git commit -m "Update CITATION.cff with latest Zenodo DOI"
                  git push origin HEAD:master
